"""SQLite DDL script generator for the compiled public contract.

Renders the CREATE TABLE and CREATE INDEX statements for all public tables into
a single ``ddl_contract.sql`` artifact. The output is derived entirely from
``CompiledTable`` objects so it stays in sync with the schema contract and the
store's live DDL automatically.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Iterable

if TYPE_CHECKING:
    from fpl_ingest.schema.compiler import CompiledTable


def generate_ddl(schema_version: str, tables: Iterable[CompiledTable]) -> str:
    """Render the full SQLite DDL script for the compiled contract."""
    rendered = [
        "-- Generated by fpl_ingest.schema.compile_contract()",
        f"-- schema_version: {schema_version}",
        "",
    ]
    for table in tables:
        rendered.append(table.create_table_sql)
        rendered.extend(table.index_sql)
        rendered.append("")
    return "\n".join(rendered).rstrip() + "\n"
