"""SQLite DDL generation for the compiled public contract."""

from __future__ import annotations

from typing import TYPE_CHECKING, Iterable

if TYPE_CHECKING:
    from fpl_ingest.contract.compiler import CompiledTable


def generate_ddl(schema_version: str, tables: Iterable[CompiledTable]) -> str:
    """Render the full SQLite DDL script for the compiled contract."""
    rendered = [
        "-- Generated by fpl_ingest.contract.compile_contract()",
        f"-- schema_version: {schema_version}",
        "",
    ]
    for table in tables:
        rendered.append(table.create_table_sql)
        rendered.extend(table.index_sql)
        rendered.append("")
    return "\n".join(rendered).rstrip() + "\n"
